### ISSUE TITLE
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 50

### ISSUE THREAD

**Issue by IhCosmo** [cdw9bf/CompactGroup#1]
Hello I'm trying to get the data but the follow error arises...

```
Traceback (most recent call last):
  File "get_data.py", line 179, in <module>
    main(args.username,args.password,
  File "get_data.py", line 121, in main
    conn.query(my_query)
  File "/media/erick/CompactGroup/data_retrieval/millennium_query.py", line 121, in query
    root = etree.fromstring(response.content)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 50
```
I tried installing another lxml version (4.20) without success... So how can I solve this little Issue?

Thanks in advace

**Comment by cdw9bf** [comment]
It's been a while since I've run this - it looks like the URL which we used to get data from has moved 
```
b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /millenniumtap/async was not found on this server.</p>\n</body></html>\n'
```

which is causing the parser error that you posted.

I'm not sure exactly where the new URL is for batch downloading of data. I looked through their website to see if I could find where the new async url is but I didn't find any references.  (http://gavo.mpa-garching.mpg.de/MyMillennium/Help)

I'd recommend reaching out to the institute and see if how they recommend proceeding, whether they have a new url or will give you access to dump the database to your machine.

**Comment by IhCosmo** [comment]
Tank you for answering. I was able to use the wget command with the SQL
sintaxis. It seems to be working.

Best regards
